import { createContext } from "react";

//Custome global context
const GlobalContext = createContext({
	theme: "",
	setTheme: () => {},
	toggleTheme: () => {},
	accentColor: "",
	setAccentColor: () => {},
	updateAccentColor: () => {},
	networkStatus: "offline",
	setNetworkStatus: () => {},
	breakpoint: () => {},
	isLoading: "",
	setIsLoading: () => {},
	snackMsg: {},
	setSnackMsg: () => {},
	showSnackBar: false,
	setShowSnackBar: () => {},
	isAuthenticated: "",
	setIsAuthenticated: () => {},
	user: undefined,
	setUser: () => {},
	verifyUser: () => {},
	updateUser: () => {},
	openSideBar: "",
	setOpenSideBar: () => {},
	toggleSideBar: () => {},
	sideBarLinks: [],
	setSideBarLinks: () => {},
	events: [],
	setEvents: () => {},
	getAllEvents: () => {},
	addOneEvent: () => {},
	updateOneEvent: () => {},
	moveOneEventToBin: () => {},
	recycleOneEvent: () => {},
	deleteOneEvent: () => {},
	notes: [],
	setNotes: () => {},
	getAllNotes: () => {},
	addOneNote: () => {},
	updateOneNote: () => {},
	archiveOneNote: () => {},
	unArchiveOneNote: () => {},
	moveOneNoteToBin: () => {},
	recycleOneNote: () => {},
	deleteOneNote: () => {},
	pinNote: () => {},
	unPinNote: () => {},
	tasks: [],
	setTasks: () => {},
	getAllTasks: () => {},
	addOneTask: () => {},
	updateOneTask: () => {},
	markTaskAsDone: () => {},
	markTaskAsNotDone: () => {},
	moveOneTaskToBin: () => {},
	recycleOneTask: () => {},
	deleteOneTask: () => {},
	getSettings: () => {},
	synchronize: () => {},
	calendarDate: "",
	setCalendarDate: () => {},
	graphQLFetch: undefined
});

export default GlobalContext;
